services:
  - type: web
    name: sandip-university-erp
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && cd sandip_university && python manage.py collectstatic --no-input && python manage.py migrate && cd .."
    startCommand: "gunicorn app:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        scope: project
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: RAZORPAY_KEY_ID
        scope: project
      - key: RAZORPAY_KEY_SECRET
        scope: project
      - key: PYTHON_VERSION
        value: "3.12"
