# Generated by Django 6.0.6 on 2026-06-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Date_of_birth', models.DateField()),
                ('course', models.CharField(choices=[('Btech', 'Btech'), ('BCA', 'BCA'), ('Polytechnic', 'Polytechnic'), ('Law', 'Law')], max_length=20)),
                ('contact_no', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
