# Generated by Django 6.0.5 on 2026-06-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='prn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
