# Generated by Django 6.0.5 on 2026-06-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_payment_order_id_payment_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='assigned_subjects',
            field=models.ManyToManyField(blank=True, related_name='assigned_to_register', to='erp.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='erp.subject'),
        ),
    ]
