# Generated by Django 6.0.5 on 2026-06-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_subject_and_assignment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.CharField(blank=True, choices=[('Btech', 'Btech'), ('BCA', 'BCA'), ('Polytechnic', 'Polytechnic'), ('Law', 'Law')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(blank=True, choices=[('Sem 1', 'Sem 1'), ('Sem 2', 'Sem 2'), ('Sem 3', 'Sem 3'), ('Sem 4', 'Sem 4'), ('Sem 5', 'Sem 5'), ('Sem 6', 'Sem 6'), ('Sem 7', 'Sem 7'), ('Sem 8', 'Sem 8')], max_length=20, null=True),
        ),
    ]
